# プロジェクトの主要言語を指定すると、AIの精度が少し向上します
language: "typescript"

# プルリクエスト全体の要約（サマリー）に対する指示
summarize_prompt: |
  このプルリクエストの主な目的と変更点を、技術的な背景がない人にも分かるように簡潔に説明してください。
  箇条書きでお願いします。
  ---
  言語は必ず日本語で出力してください。

# ファイルごとのコードレビューに対する指示
review_file_prompt: |
  あなたは経験豊富なソフトウェアエンジニアです。
  以下のコード変更をレビューし、SOLID原則やクリーンアーキテクチャの観点から、
  改善できる点があれば具体的に提案してください。
  特に問題がなければ、その旨を伝えてください。
  ---
  言語は必ず日本語で出力してください。
